version: "3.4"

services:
  celery-service:
    image: "celery-service:latest"
    ports: 
      - "5000:5000"
    env_file:
    - .env.docker

  redis:
    image: "redis:6.0.8-alpine"
    deploy:
      restart_policy:
        condition: on-failure
    expose:
      - "6379"